export const defaultIssues = [
  { name: "Supplier Emissions (Scope 3)", category: "Environmental" },
  { name: "Energy Procurement (Scope 2)", category: "Environmental" },
  { name: "Direct Fuel & Process Emissions (Scope 1)", category: "Environmental" },
  { name: "Business Travel & Employee Commuting", category: "Environmental" },
  { name: "Waste Management & Circular Economy", category: "Environmental" },
  { name: "Water Usage & Stewardship", category: "Environmental" },
  { name: "Biodiversity & Land Use", category: "Environmental" },
  { name: "Climate Physical Risk (Extreme Weather)", category: "Environmental" },
  { name: "Climate Transition Risk (Policy / Market Shift)", category: "Environmental" },
  { name: "Workforce Health & Safety", category: "Social" },
  { name: "Diversity, Equity & Inclusion", category: "Social" },
  { name: "Community Impact & Engagement", category: "Social" },
  { name: "Supply Chain Human Rights", category: "Social" },
  { name: "Board ESG Oversight & Governance", category: "Governance" },
  { name: "Anti-Corruption & Business Ethics", category: "Governance" },
  { name: "Data Privacy & Cybersecurity", category: "Governance" },
];

export const industryOptions = [
  "Manufacturing",
  "Energy & Utilities",
  "Oil & Gas",
  "Retail & Consumer Goods",
  "Financial Services",
  "Technology",
  "Healthcare & Pharmaceuticals",
  "Construction & Real Estate",
  "Transportation & Logistics",
  "Agriculture & Food",
  "Mining & Metals",
  "Telecommunications",
  "Professional Services",
  "Other",
];
